//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerSeat통합검사기.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short LIN_DEVICE {
            get {
                return ((short)(this["LIN_DEVICE"]));
            }
            set {
                this["LIN_DEVICE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LIN_SPEED {
            get {
                return ((int)(this["LIN_SPEED"]));
            }
            set {
                this["LIN_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short CAN_CHANNEL {
            get {
                return ((short)(this["CAN_CHANNEL"]));
            }
            set {
                this["CAN_CHANNEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short CAN_DEVICE {
            get {
                return ((short)(this["CAN_DEVICE"]));
            }
            set {
                this["CAN_DEVICE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short CAN_ID {
            get {
                return ((short)(this["CAN_ID"]));
            }
            set {
                this["CAN_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CAN_SPEED {
            get {
                return ((int)(this["CAN_SPEED"]));
            }
            set {
                this["CAN_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MES_IP {
            get {
                return ((string)(this["MES_IP"]));
            }
            set {
                this["MES_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MES_PORT {
            get {
                return ((int)(this["MES_PORT"]));
            }
            set {
                this["MES_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MES_SERVER_IP {
            get {
                return ((string)(this["MES_SERVER_IP"]));
            }
            set {
                this["MES_SERVER_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MES_SERVER_PORT {
            get {
                return ((int)(this["MES_SERVER_PORT"]));
            }
            set {
                this["MES_SERVER_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM4")]
        public string P_METER_PORT {
            get {
                return ((string)(this["P_METER_PORT"]));
            }
            set {
                this["P_METER_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int P_METER_SPEED {
            get {
                return ((int)(this["P_METER_SPEED"]));
            }
            set {
                this["P_METER_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.8")]
        public string IO_BOARD_IP {
            get {
                return ((string)(this["IO_BOARD_IP"]));
            }
            set {
                this["IO_BOARD_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8000")]
        public int IO_BOARD_PORT {
            get {
                return ((int)(this["IO_BOARD_PORT"]));
            }
            set {
                this["IO_BOARD_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.200")]
        public string PC_IP {
            get {
                return ((string)(this["PC_IP"]));
            }
            set {
                this["PC_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6500")]
        public int PC_PORT {
            get {
                return ((int)(this["PC_PORT"]));
            }
            set {
                this["PC_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int BATTID {
            get {
                return ((int)(this["BATTID"]));
            }
            set {
                this["BATTID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int BUCKLEID {
            get {
                return ((int)(this["BUCKLEID"]));
            }
            set {
                this["BUCKLEID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int HEATERID {
            get {
                return ((int)(this["HEATERID"]));
            }
            set {
                this["HEATERID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM2")]
        public string POWER_PORT {
            get {
                return ((string)(this["POWER_PORT"]));
            }
            set {
                this["POWER_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int POWER_SPEED {
            get {
                return ((int)(this["POWER_SPEED"]));
            }
            set {
                this["POWER_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short LIN_DEVICE2 {
            get {
                return ((short)(this["LIN_DEVICE2"]));
            }
            set {
                this["LIN_DEVICE2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LIN_SPEED2 {
            get {
                return ((int)(this["LIN_SPEED2"]));
            }
            set {
                this["LIN_SPEED2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short CAN_CHANNEL2 {
            get {
                return ((short)(this["CAN_CHANNEL2"]));
            }
            set {
                this["CAN_CHANNEL2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short CAN_DEVICE2 {
            get {
                return ((short)(this["CAN_DEVICE2"]));
            }
            set {
                this["CAN_DEVICE2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short CAN_ID2 {
            get {
                return ((short)(this["CAN_ID2"]));
            }
            set {
                this["CAN_ID2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CAN_SPEED2 {
            get {
                return ((int)(this["CAN_SPEED2"]));
            }
            set {
                this["CAN_SPEED2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string IO_CARD_PORT {
            get {
                return ((string)(this["IO_CARD_PORT"]));
            }
            set {
                this["IO_CARD_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int IO_CARD_SPEED {
            get {
                return ((int)(this["IO_CARD_SPEED"]));
            }
            set {
                this["IO_CARD_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MULTIMETER_PORT {
            get {
                return ((string)(this["MULTIMETER_PORT"]));
            }
            set {
                this["MULTIMETER_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MULTIMETER_SPEED {
            get {
                return ((int)(this["MULTIMETER_SPEED"]));
            }
            set {
                this["MULTIMETER_SPEED"] = value;
            }
        }
    }
}
